- hosts: k3s
  become: yes
  roles:
  - { role: firstvds_common, tags: common }

- hosts: k3s
  vars:
    k3s_server:
      disable:
        - traefik
  pre_tasks:
    - name: Set each node to be a control node
      ansible.builtin.set_fact:
        k3s_control_node: true
      when: inventory_hostname in ['k3s-master-1']
  roles:
  - { role: xanmanning.k3s, tags: k3s }
  - { role: k3s_config, tags: k3s_config }
